import { chmodSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

/**
 * Shell access to `pixlstash-cli` for desktop installs.
 *
 * The CLI is the only way to attach a library or install a plugin, and a
 * packaged desktop build hides it twice over: the console script lives inside
 * the app image (an AppImage is a squashfs mounted at a *different random path
 * every launch*, and unmounted the moment the app exits), and the desktop's hub
 * is not the platform default one — it sits beside the desktop's own
 * `server-config.json`, so a bare `pixlstash-cli` would edit the wrong
 * registry.
 *
 * Both problems are solved by making the app its own CLI entry point: launching
 * it with a leading `cli` argument runs the module inside the bundled runtime,
 * against the right hub, and exits without ever opening a window (see
 * `parseCliArgs` and its caller in main.ts). The launcher path is stable — for
 * an AppImage it is the `.AppImage` file itself, which the runtime hands us in
 * `$APPIMAGE` — so a one-line `exec` script is enough to put it on PATH.
 */

/** First line of the generated script; also how we recognise our own file. */
const MARKER = '# Generated by PixlStash. Safe to delete.';

/** Where the shim goes: the XDG-conventional per-user bin dir. */
export function shimPath(home: string = homedir()): string {
  return join(home, '.local', 'bin', 'pixlstash');
}

/** Single-quote *value* for `sh`, closing and reopening around any quote. */
function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * The shim's contents: exec the app's own launcher with the `cli` marker.
 *
 * `exec` rather than a plain call so the shell is replaced and the exit status
 * (which the CLI uses: 1 refusal, 2 usage, 3 hub unavailable) reaches the caller
 * unchanged.
 */
export function shimScript(launcher: string): string {
  return `#!/bin/sh\n${MARKER}\nexec ${shQuote(launcher)} cli "$@"\n`;
}

/**
 * The app's own launcher, as a path a shell can run later.
 *
 * `$APPIMAGE` is set by the AppImage runtime and points at the `.AppImage` file
 * the user actually keeps; `process.execPath` inside one would point into the
 * throwaway mount instead. Everywhere else (deb, .app) execPath *is* the
 * durable path.
 */
export function launcherPath(env: NodeJS.ProcessEnv = process.env, execPath = process.execPath): string {
  return env.APPIMAGE || execPath;
}

/**
 * The command to teach the user, given whether the shim is installed.
 *
 * Handed to the backend as `PIXLSTASH_CLI_COMMAND` so `pixlstash.hub.cli_hint`
 * can print something that actually runs. Without the shim the full launcher
 * path is still a working command — unlike the bare console-script name, which
 * is on no PATH — so the Settings hint is correct either way.
 */
export function cliCommandHint(shimInstalled: boolean, launcher: string): string {
  return shimInstalled ? 'pixlstash' : `${shQuote(launcher)} cli`;
}

/**
 * Whether our shim is on disk right now, without touching it.
 *
 * The CLI path needs the answer to name itself correctly, and a CLI run must
 * never install anything as a side effect. Checks for our marker so a
 * `pixlstash` the user wrote themselves is not mistaken for ours.
 */
export function shimInstalled(path: string = shimPath()): boolean {
  try {
    return readFileSync(path, 'utf8').includes(MARKER);
  } catch {
    return false;
  }
}

/**
 * Whether something that is not ours already occupies the shim path.
 *
 * A `pixlstash` the user put on their own PATH is theirs, and this writes
 * outside the app's own storage, so an occupied path is a refusal rather than
 * an overwrite. Reported separately from {@link syncShim}'s boolean so the
 * caller can say *why* enabling did nothing.
 */
export function shimBlocked(path: string = shimPath()): boolean {
  try {
    return !readFileSync(path, 'utf8').includes(MARKER);
  } catch {
    // Missing (the normal case) or unreadable: nothing of the user's is being
    // displaced either way, so this is not the blocked condition.
    return false;
  }
}

/**
 * Bring `~/.local/bin/pixlstash` in line with *enabled*.
 *
 * Rewritten on every launch rather than once at install time, so moving or
 * renaming the AppImage repairs the shim instead of leaving a script that execs
 * a file that is no longer there.
 *
 * A file that is not ours is never touched, in either direction: enabling
 * refuses rather than overwriting it, and disabling leaves it alone. Returns
 * whether *our* shim is present afterwards.
 */
export function syncShim(enabled: boolean, launcher: string, path: string = shimPath()): boolean {
  try {
    if (!enabled) {
      if (readFileSync(path, 'utf8').includes(MARKER)) rmSync(path);
      return false;
    }
    if (shimBlocked(path)) {
      console.warn(`[cli-shim] ${path} was not created by PixlStash; leaving it alone`);
      return false;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, shimScript(launcher));
    chmodSync(path, 0o755);
    return true;
  } catch (e) {
    // ENOENT on the remove path is the normal "nothing to clean up" case; a
    // read-only home is the interesting one, and neither is worth blocking
    // startup over.
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn('[cli-shim] could not update the shell command:', e);
    }
    return false;
  }
}

/**
 * The CLI arguments in *argv*, or null for a normal windowed launch.
 *
 * A bare `cli` token marks the boundary; everything after it belongs to the
 * Python CLI. Searched from index 1 so the executable's own path can never be
 * mistaken for the marker, and so the dev launch (`electron . cli …`, where
 * argv[1] is the app directory) works the same as the packaged one.
 */
export function parseCliArgs(argv: readonly string[]): string[] | null {
  const at = argv.indexOf('cli', 1);
  return at === -1 ? null : argv.slice(at + 1);
}
