import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

/**
 * Shell access to `pixlstash-cli` for desktop installs.
 *
 * The CLI is the only way to attach a library or install a plugin, and a
 * packaged desktop build hides it twice over: the console script lives inside
 * the app image (an AppImage is a squashfs mounted at a *different random path
 * every launch*, and unmounted the moment the app exits), and the desktop's hub
 * is not the platform default one — it sits beside the desktop's own
 * `server-config.json`, so a bare `pixlstash-cli` would edit the wrong
 * registry.
 *
 * Both problems are solved by making the app its own CLI entry point: launching
 * it with a leading `cli` argument runs the module inside the bundled runtime,
 * against the right hub, and exits without ever opening a window (see
 * `parseCliArgs` and its caller in main.ts). The launcher path is stable — for
 * an AppImage it is the `.AppImage` file itself, which the runtime hands us in
 * `$APPIMAGE` — so a one-line `exec` script is enough to put it on PATH.
 *
 * Windows takes the other route (issue #1060). Its launcher is linked for the
 * GUI subsystem, so no shell waits for it; the shim there is a `.cmd`
 * forwarding to the bundled console-subsystem `python.exe` against the
 * desktop's own hub — the same invocation `runCli` spawns and
 * `desktop_windows_command` prints. Windows also has no per-user bin directory
 * already on PATH, so the shim's own directory is appended to the user's PATH
 * (see {@link syncUserPath}).
 */

/** Comment text in the generated script; also how we recognise our own file. */
const MARKER = 'Generated by PixlStash. Safe to delete.';

/**
 * Where the shim goes: the XDG-conventional per-user bin dir, or — on Windows,
 * which has none — a bin directory of our own under `%LOCALAPPDATA%`, which
 * {@link syncUserPath} then appends to the user's PATH.
 */
export function shimPath(
  home: string = homedir(),
  platform: NodeJS.Platform = process.platform,
): string {
  if (platform !== 'win32') return join(home, '.local', 'bin', 'pixlstash');
  return join(process.env.LOCALAPPDATA || join(home, 'AppData', 'Local'), 'PixlStash', 'bin', 'pixlstash.cmd');
}

/** Single-quote *value* for `sh`, closing and reopening around any quote. */
function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Double-quote *value* for a batch file, escaping the one metacharacter it has. */
function cmdQuote(value: string): string {
  // Windows paths cannot contain a quote, so only `%` needs handling: batch
  // percent-expansion turns `%%` back into a literal `%`.
  return `"${value.replace(/%/g, '%%')}"`;
}

/**
 * The shim's contents: forward to the CLI, keeping the caller's exit status.
 *
 * POSIX `exec`s the app's own launcher with the `cli` marker, replacing the
 * shell so the status (which the CLI uses: 1 refusal, 2 usage, 3 hub
 * unavailable) reaches the caller unchanged. Windows cannot use the launcher at
 * all — it is a GUI-subsystem binary no shell waits for — so *windowsHub*
 * selects a `.cmd` calling the bundled interpreter directly, with `exit /b`
 * doing what `exec` does elsewhere. CRLF because a batch file with bare LFs is
 * read inconsistently by cmd.
 *
 * The `.cmd` also names itself in `PIXLSTASH_CLI_COMMAND`, because it bypasses
 * the Electron launcher that would otherwise declare it: without this the CLI's
 * own usage lines would print the long bundled-interpreter command instead of
 * the bare word the user just typed. `setlocal` keeps that out of the calling
 * shell, which is the same process when a `.cmd` is run interactively.
 */
export function shimScript(launcher: string, windowsHub?: string): string {
  if (windowsHub === undefined) {
    return `#!/bin/sh\n# ${MARKER}\nexec ${shQuote(launcher)} cli "$@"\n`;
  }
  return [
    '@echo off',
    `REM ${MARKER}`,
    'setlocal',
    'set "PIXLSTASH_CLI_COMMAND=pixlstash"',
    `${cmdQuote(launcher)} -m pixlstash.cli --hub ${cmdQuote(windowsHub)} %*`,
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\r\n');
}

/**
 * The app's own launcher, as a path a shell can run later.
 *
 * `$APPIMAGE` is set by the AppImage runtime and points at the `.AppImage` file
 * the user actually keeps; `process.execPath` inside one would point into the
 * throwaway mount instead. Everywhere else (deb, .app) execPath *is* the
 * durable path.
 */
export function launcherPath(env: NodeJS.ProcessEnv = process.env, execPath = process.execPath): string {
  return env.APPIMAGE || execPath;
}

/**
 * The command to teach the user, given whether the shim is installed.
 *
 * Handed to the backend as `PIXLSTASH_CLI_COMMAND` so `pixlstash.hub.cli_hint`
 * can print something that actually runs. Without the shim the full launcher
 * path is still a working command — unlike the bare console-script name, which
 * is on no PATH — so the Settings hint is correct either way.
 */
export function cliCommandHint(shimInstalled: boolean, launcher: string): string {
  return shimInstalled ? 'pixlstash' : `${shQuote(launcher)} cli`;
}

/**
 * Whether our shim is on disk right now, without touching it.
 *
 * The CLI path needs the answer to name itself correctly, and a CLI run must
 * never install anything as a side effect. Checks for our marker so a
 * `pixlstash` the user wrote themselves is not mistaken for ours.
 */
export function shimInstalled(path: string = shimPath()): boolean {
  try {
    return readFileSync(path, 'utf8').includes(MARKER);
  } catch {
    return false;
  }
}

/**
 * Whether something that is not ours already occupies the shim path.
 *
 * A `pixlstash` the user put on their own PATH is theirs, and this writes
 * outside the app's own storage, so an occupied path is a refusal rather than
 * an overwrite. Reported separately from {@link syncShim}'s boolean so the
 * caller can say *why* enabling did nothing.
 */
export function shimBlocked(path: string = shimPath()): boolean {
  try {
    return !readFileSync(path, 'utf8').includes(MARKER);
  } catch {
    // Missing (the normal case) or unreadable: nothing of the user's is being
    // displaced either way, so this is not the blocked condition.
    return false;
  }
}

/**
 * Bring the shim file in line with *enabled*.
 *
 * Rewritten on every launch rather than once at install time, so moving or
 * renaming the AppImage repairs the shim instead of leaving a script that execs
 * a file that is no longer there.
 *
 * A file that is not ours is never touched, in either direction: enabling
 * refuses rather than overwriting it, and disabling leaves it alone. Returns
 * whether *our* shim is present afterwards.
 *
 * *windowsHub* selects the `.cmd` form — see {@link shimScript}.
 */
export function syncShim(
  enabled: boolean,
  launcher: string,
  path: string = shimPath(),
  windowsHub?: string,
): boolean {
  try {
    if (!enabled) {
      if (readFileSync(path, 'utf8').includes(MARKER)) rmSync(path);
      return false;
    }
    if (shimBlocked(path)) {
      console.warn(`[cli-shim] ${path} was not created by PixlStash; leaving it alone`);
      return false;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, shimScript(launcher, windowsHub));
    // Windows has no execute bit; the `.cmd` extension is what makes it runnable.
    if (windowsHub === undefined) chmodSync(path, 0o755);
    return true;
  } catch (e) {
    // ENOENT on the remove path is the normal "nothing to clean up" case; a
    // read-only home is the interesting one, and neither is worth blocking
    // startup over.
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn('[cli-shim] could not update the shell command:', e);
    }
    return false;
  }
}

/** The per-user environment block. Per-user, so no elevation is ever needed. */
const USER_ENV_KEY = 'HKCU\\Environment';

/** Whether two PATH elements name the same directory, as Windows compares them. */
function samePathElement(a: string, b: string): boolean {
  const normalise = (p: string) => p.trim().replace(/\\+$/, '').toLowerCase();
  return normalise(a) === normalise(b);
}

/**
 * *value* with *dir* appended, or null when it is already there.
 *
 * Null rather than an unchanged string so the caller can skip the registry
 * write entirely — which is what makes enabling twice leave exactly one entry,
 * and what keeps every subsequent launch from rewriting a PATH it agrees with.
 */
export function pathWith(value: string, dir: string): string | null {
  if (value.split(';').some((p) => samePathElement(p, dir))) return null;
  return value.trim() === '' ? dir : `${value.replace(/;+$/, '')};${dir}`;
}

/** *value* with every occurrence of *dir* removed, or null when it holds none. */
export function pathWithout(value: string, dir: string): string | null {
  const parts = value.split(';');
  const kept = parts.filter((p) => !samePathElement(p, dir));
  return kept.length === parts.length ? null : kept.join(';');
}

/**
 * The user's `Path`, unexpanded, or null when the value does not exist.
 *
 * `reg query` prints the stored data verbatim, so a REG_EXPAND_SZ still carries
 * its `%VARS%` — which is why the read/modify/write goes through reg.exe rather
 * than `setx` or .NET's SetEnvironmentVariable, both of which would bake the
 * expansions in and flatten REG_EXPAND_SZ to REG_SZ.
 *
 * Throws rather than returning anything it is not certain it read correctly,
 * because the caller treats "no value" as an empty PATH and would then write
 * ours as the only element. Two ways that could go wrong, both closed here:
 *
 * - `reg query /v Path` exits non-zero for an absent value AND for a failed
 *   read, and the exit code does not say which. So we query the whole key
 *   instead: `HKCU\Environment` always exists for a signed-in user, which makes
 *   a non-zero exit unambiguously a failure and an absent `Path` row
 *   unambiguously an absent value.
 * - reg.exe writes a pipe in the console's OEM code page and we decode it as
 *   UTF-8, so a PATH holding `Ø` would come back as a replacement character and
 *   writing it back would corrupt the value. Every byte of a Windows PATH we
 *   could safely round-trip is printable ASCII; anything else means the decode
 *   is not trustworthy and the right move is to touch nothing.
 */
function readUserPath(): { name: string; kind: string; value: string } | null {
  const reg = spawnSync('reg', ['query', USER_ENV_KEY], { encoding: 'utf8' });
  if (reg.error) throw reg.error;
  if (reg.status !== 0) {
    throw new Error(`reg query ${USER_ENV_KEY} exited ${reg.status}: ${reg.stderr}`);
  }
  const m = reg.stdout.match(/^\s*(Path)\s+(REG_\w+)\s+(.*)$/im);
  if (!m) return null;
  const value = m[3].trimEnd();
  if (/[^\x20-\x7e]/.test(value)) {
    throw new Error('the user PATH did not decode as ASCII; refusing to rewrite it');
  }
  return { name: m[1], kind: m[2], value };
}

/**
 * Tell already-running processes that the environment changed.
 *
 * Without this, PATH lands in the registry but Explorer keeps handing its own
 * stale copy to everything it launches, so even a freshly opened terminal would
 * not see the shim until the next sign-in. Best-effort: a failure costs the
 * user one sign-out, which is what the Settings row already warns about.
 */
function broadcastEnvChange(): void {
  const signature =
    '[DllImport("user32.dll")] public static extern IntPtr SendMessageTimeout(' +
    'IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint flags, uint timeout, out UIntPtr result);';
  // HWND_BROADCAST (0xffff), WM_SETTINGCHANGE (0x1a), SMTO_ABORTIFHUNG (2).
  const script =
    `Add-Type -Namespace Pixl -Name Env -MemberDefinition '${signature}'; ` +
    '$r = [UIntPtr]::Zero; ' +
    "[Pixl.Env]::SendMessageTimeout([IntPtr]0xffff, 0x1a, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$r) | Out-Null";
  // Asynchronous rather than spawnSync: Add-Type compiles C# on the fly and can
  // take seconds, and this runs on the toggle's IPC handler, which is the main
  // thread. The registry write has already happened by here, so nothing waits on
  // the answer — but the exit status is still reported, because Add-Type is
  // refused outright under Constrained Language Mode (AppLocker/WDAC) and a
  // silent failure there looks exactly like success.
  const warn = (why: unknown) =>
    console.warn('[cli-shim] could not announce the PATH change; a sign-out will pick it up:', why);
  const ps = spawn('powershell', ['-NoProfile', '-NonInteractive', '-Command', script], {
    stdio: 'ignore',
    // Not `detached`: on Windows that gives the child its own console, which
    // flashes a black window at the user on every toggle.
    windowsHide: true,
  });
  ps.on('error', warn);
  ps.on('exit', (code) => {
    if (code !== 0) warn(`powershell exited ${code}`);
  });
  ps.unref();
}

/**
 * Add or remove *dir* in the user's PATH. Windows only; a no-op elsewhere.
 *
 * Only the element we added is ever removed, and the rest of the value is
 * written back byte-for-byte, because this is the user's PATH and not the app's
 * storage. Returns whether *dir* is on the user PATH afterwards.
 */
export function syncUserPath(enabled: boolean, dir: string, platform: NodeJS.Platform = process.platform): boolean {
  if (platform !== 'win32') return false;
  try {
    const current = readUserPath();
    const next = enabled
      ? pathWith(current?.value ?? '', dir)
      : pathWithout(current?.value ?? '', dir);
    if (next === null) return enabled; // already in the state we want
    const name = current?.name ?? 'Path';
    // An empty value would be a `Path` set to the empty string; removing the
    // value is what "the user had nothing but us" actually means.
    const args =
      next === ''
        ? ['delete', USER_ENV_KEY, '/v', name, '/f']
        : ['add', USER_ENV_KEY, '/v', name, '/t', current?.kind ?? 'REG_EXPAND_SZ', '/d', next, '/f'];
    const reg = spawnSync('reg', args, { encoding: 'utf8' });
    if (reg.status !== 0) throw new Error(`reg ${args[0]} exited ${reg.status}: ${reg.stderr}`);
    broadcastEnvChange();
    return enabled;
  } catch (e) {
    console.warn('[cli-shim] could not update the user PATH:', e);
    return false;
  }
}

/**
 * The CLI arguments in *argv*, or null for a normal windowed launch.
 *
 * A bare `cli` token marks the boundary; everything after it belongs to the
 * Python CLI. Searched from index 1 so the executable's own path can never be
 * mistaken for the marker, and so the dev launch (`electron . cli …`, where
 * argv[1] is the app directory) works the same as the packaged one.
 */
export function parseCliArgs(argv: readonly string[]): string[] | null {
  const at = argv.indexOf('cli', 1);
  return at === -1 ? null : argv.slice(at + 1);
}
