"""Recompute smart scores left stale by tag edits made before invalidation existed.

``Picture.smart_score`` is a cached derived column and ``MissingSmartScoreFinder`` only
picks up pictures whose score is ``NULL``, so a stored score was previously never
recomputed. Its anomaly-penalty term, however, is a live function of the anomaly-tag
predictions, so every tag refresh or manual anomaly-tag edit since the score was first
computed left the stored value silently wrong.

The code fix invalidates the score whenever a picture's anomaly state actually changes
(``pixlstash.utils.service.smart_score_invalidation``), but that only covers edits made
from now on. Scores already stale in an existing database cannot heal themselves, so this
migration NULL-resets the column once; the finder then recomputes every picture against
its current anomaly-tag state on the next run. Mirrors
``0062_recompute_smart_score_calibrated_anomaly``. Schema-only otherwise — no columns are
added or removed.

Revision ID: 0076_recompute_smart_score_after_stale_tag_edits
Revises: 0075_add_tag_health_ground_truth
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0076_recompute_smart_score_after_stale_tag_edits"
down_revision: Union[str, None] = "0075_add_tag_health_ground_truth"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes against each picture's current anomaly-tag state.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
