"""Recompute smart scores after the graded anomaly aggregation and soft score floor.

``Picture.smart_score`` is a cached derived column and ``MissingSmartScoreFinder`` only
picks up pictures whose score is ``NULL``, so stored scores never recompute on their own.
Two scoring changes invalidate every stored value:

* The anomaly penalty no longer runs noisy-OR across a whole family with the family's
  maximum member weight. Distinct defects now accumulate with a rank decay and each tag
  contributes its *own* weight, so defect count and per-tag severity both move the score
  (``pixlstash.utils.quality.anomaly_penalty``).
* The raw score is soft-compressed into ``[0, 1]`` instead of hard-clipped, so pictures
  that previously tied at exactly 1.0 keep their ordering
  (``pixlstash.utils.quality.smart_score_utils.compress_raw_score``).

Every stored score therefore predates the current formula. This migration NULL-resets the
column once; the finder recomputes each picture against the new aggregation on the next
run. Mirrors ``0076_recompute_smart_score_after_stale_tag_edits``. Schema-only otherwise —
no columns are added or removed.

Revision ID: 0077_recompute_smart_score_graded_anomaly_aggregation
Revises: 0076_recompute_smart_score_after_stale_tag_edits
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0077_recompute_smart_score_graded_anomaly_aggregation"
down_revision: Union[str, None] = "0076_recompute_smart_score_after_stale_tag_edits"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes under the graded aggregation and soft floor.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
