"""Recompute smart scores after honouring user penalised-tag weights and the apply gate.

``Picture.smart_score`` is a cached derived column and ``MissingSmartScoreFinder`` only
picks up pictures whose score is ``NULL``, so stored scores never recompute on their own.
Two scoring fixes invalidate every stored value:

* The anomaly penalty now uses the *user's* ``User.smart_score_penalised_tags`` weights
  instead of the hardcoded ``DEFAULT_SMART_SCORE_PENALIZED_TAGS`` seed, which was baked
  into a module-level table at import time. A tag the user removed is no longer charged
  at all, and per-tag severity plus the per-family ceiling both follow the user's table
  (``pixlstash.utils.quality.anomaly_penalty``).
* Only predictions that clear the tagger's per-label acceptance threshold are penalised,
  so a picture is no longer pushed down by sub-threshold predictions that never became
  visible tags. Human POS/NEG decisions are still honoured regardless of confidence
  (``pixlstash.picture_scoring.fetch_anomaly_confidences``).

Every stored score therefore predates the current formula. This migration NULL-resets the
column once; the finder recomputes each picture on the next run. Mirrors
``0077_recompute_smart_score_graded_anomaly_aggregation``. Schema-only otherwise — no
columns are added or removed.

Revision ID: 0078_recompute_smart_score_user_penalised_tags_and_apply_threshold
Revises: 0077_recompute_smart_score_graded_anomaly_aggregation
Create Date: 2026-07-19 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0078_recompute_smart_score_user_penalised_tags_and_apply_threshold"
down_revision: Union[str, None] = (
    "0077_recompute_smart_score_graded_anomaly_aggregation"
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes under the user's own penalised-tag weights and the
    # tagger's apply threshold.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
