"""Recompute smart scores after grading anomaly confidence relative to the apply gate.

``Picture.smart_score`` is a cached derived column and ``MissingSmartScoreFinder`` only
picks up pictures whose score is ``NULL``, so stored scores never recompute on their own.

The anomaly penalty now reads a detection's confidence *relative to that tag's own
acceptance threshold* rather than in absolute terms. The scorer only ever sees predictions
that already cleared the gate, so a tag's usable range is ``[threshold, 1.0]`` and the
threshold differs per label (0.5-0.85 on the shipped model once the user's
``threshold_offset`` is applied). Confidence is normalised onto that range before the
:data:`~pixlstash.utils.quality.anomaly_penalty.CONF_POWER` exponent (raised 1.5 -> 3.0),
so a barely-accepted detection is charged
:data:`~pixlstash.utils.quality.anomaly_penalty.EVIDENCE_FLOOR` of full severity while a
near-certain one is charged in full — and "just over the line" now means the same thing
for a tag gated at 0.50 as for one gated at 0.85.

The shaping is an identity at confidence 1.0, so the calibrated defect-count bands from
``0077_recompute_smart_score_graded_anomaly_aggregation`` are unchanged at full
confidence; what moves is every stored score derived from a sub-certain detection. This
migration NULL-resets the column once; the finder recomputes each picture on the next run.
Schema-only otherwise — no columns are added or removed.

Revision ID: 0079_recompute_smart_score_threshold_relative_confidence
Revises: 0078_recompute_smart_score_user_penalised_tags_and_apply_threshold
Create Date: 2026-07-19 21:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0079_recompute_smart_score_threshold_relative_confidence"
down_revision: Union[str, None] = (
    "0078_recompute_smart_score_user_penalised_tags_and_apply_threshold"
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes with threshold-relative confidence grading.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
