"""Recompute smart scores after restoring the built-in anchors.

``_load_builtin_anchors`` read its assets from ``Path(__file__).parent / "data" /
"anchors"``. The Phase 2 scoring split (``2d14952d``) moved that loader from
``pixlstash/picture_scoring.py`` down into ``pixlstash/scoring/smart_score.py`` and carried
the relative path over unchanged, so it resolved to ``pixlstash/scoring/data/anchors`` --
a directory that has never existed. The loader returned two empty lists and said so at
``logger.debug``, which nothing surfaces, so the built-in anchors were silently absent for
the whole 1.8.0 pre-release.

They are supplemented into the anchor set whenever the owner has fewer than
``_BUILTIN_MIN_GOOD`` good or ``_BUILTIN_MIN_BAD`` bad ratings, which is the common case
and the entire point of shipping them: a library with few ratings has no other signal.
Every score computed for such a library was therefore computed without them and is stale.

The reset cannot be scoped to those libraries. Whether the supplement applied depends on
the rating counts at the time each score was written, which is not recorded, so a
per-picture decision is not derivable. Resetting everything is correct and also avoids the
worse outcome: a library holding stale scores beside corrected ones, which would corrupt
sort order and the agreement chart while looking fine.

``MissingSmartScoreFinder`` picks the NULLed rows up on the next run. Schema-only
otherwise -- no columns are added or removed.

Revision ID: 0085_recompute_smart_score_restored_builtin_anchors
Revises: 0084_recompute_smart_score_rebalanced_weights
Create Date: 2026-07-26 22:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0085_recompute_smart_score_restored_builtin_anchors"
down_revision: Union[str, None] = "0084_recompute_smart_score_rebalanced_weights"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    if "smart_score" not in {c["name"] for c in inspector.get_columns("picture")}:
        return
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
