from .pixl_logging import get_logger

logger = get_logger(__name__)


class TagNaturaliser:
    TAG_MAP = {
        'back-print_panties': 'panties with back print',
        'dual_wielding': 'holding two weapons at once',
        'elezen': 'elezen (race)',
        'nata_(tool)': 'nata (japanese hatchet)',
        'wakizashi': 'wakizashi (short sword)',
        'squidbeak_splatoon': 'squidbeak (splatoon)',
        'upshirt': 'shirt lifted up',
        'necktie_grab': 'grabbing necktie',
        'yin_yang_orb': 'yin-yang orb',
        'heart_balloon': 'heart-shaped balloon',
        'asa_no_ha_(pattern)': 'asa no ha (hemp leaf pattern)',
        '2000s_(style)': '2000s style',
        'survey_corps_(emblem)': 'survey corps emblem',
        'poke_ball_theme': 'poké ball theme',
        'sig_sauer': 'sig sauer (firearm)',
        'belly_grab': 'grabbing belly',
        'heart_o-ring': 'heart-shaped o-ring',
        'crocodilian_tail': 'crocodile tail',
        'kaijuu': 'kaijuu (monster)',
        'print_headwear': 'printed headwear',
        'tantou': 'tantou (short sword)',
        'tonfa': 'tonfa (baton)',
        'furigana': 'furigana (reading aid)',
        '_+': 'excited face emoticon',
        "st._gloriana's_(emblem)": "st. gloriana's emblem",
        'panzerkampfwagen_iv': 'panzerkampfwagen iv (tank)',
        'naked_overalls': 'naked with overalls',
        'zabuton': 'zabuton (floor cushion)',
        'in_cup': 'in a cup',
        'good_end': 'good ending',
        'calico': 'calico (cat)',
        'handgun': 'small firearm',
        'breasts_apart': 'breasts positioned apart',
        'hanten_(clothes)': 'hanten (short winter coat)',
        'hands_on_own_ass': 'hands on own butt',
        'cd': 'cd (compact disc)',
        'square_4koma': 'square 4-panel comic',
        'dudou': 'dudou (chinese undergarment)',
        '>o<': 'angry face',
        'eyewear_hang': 'eyewear hanging',
        'telstar': 'telstar (soccer ball)',
        'cat_ear_legwear': 'legwear with cat ears',
        'alice_(alice_in_wonderland)_(cosplay)': 'alice (alice in wonderland) cosplay',
        'footwear_ribbon': 'footwear with ribbon',
        'kine': 'kine (rice pounder)',
        'print_jacket': 'printed jacket',
        'kepi': 'kepi (military cap)',
        'naked_scarf': 'naked with scarf',
        'bokken': 'bokken (wooden sword)',
        'lowleg_pants': 'low-leg pants',
        'polka_dot_headwear': 'headwear with polka dots',
        'boobplate': 'boobplate (armor)',
        'hanbok': 'hanbok (korean dress)',
        'voile': 'voile (fabric)',
        'mash_kyrielight_(dangerous_beast)_(cosplay)': 'mash kyrielight (dangerous beast) cosplay',
        'child_drawing': "child's drawing",
        'akanbe': 'akanbe (taunt)',
        'ar-15': 'ar-15 (rifle)',
        'haniwa_(statue)': 'haniwa (clay statue)',
        'houndstooth': 'houndstooth pattern',
        'lace-trimmed_hairband': 'hairband with lace trim',
        'bandaid_on_forehead': 'bandage on forehead',
        'dress_flower': 'flower on dress',
        'henshin': 'henshin (transformation)',
        'print_shorts': 'printed shorts',
        'kouhaku_nawa': 'kouhaku nawa (red and white rope)',
        'visor_(armor)': 'armor visor',
        'monster_energy': 'monster energy (brand)',
        '<o>_<o>': 'surprised face (<o>_<o>)',
        'elvaan': 'elvaan (race)',
        'oda_uri': 'oda uri (unknown context)',
        'adidas': 'adidas (brand)',
        'painterly': 'painterly style',
        'side_slit_shorts': 'side-slit shorts',
        'm1911': 'm1911 (pistol)',
        'ultra_ball': 'ultra ball (pokémon)',
        'x3': 'happy face (x3)',
        'araki_hirohiko_(style)': 'araki hirohiko style',
        'hishaku': 'hishaku (water ladle)',
        'hatsune_miku_(cosplay)': 'hatsune miku cosplay',
        'hamaya': 'hamaya (ceremonial arrow)',
        'single_pantsleg': 'single pants leg',
        'pokemon_on_shoulder': 'pokémon on shoulder',
        'animal_ear_legwear': 'legwear with animal ears',
        'bad_end': 'bad ending',
        'power_suit_(metroid)': 'metroid power suit',
        'alphes_(style)': 'alphes style',
        'mithra_(ff11)': 'mithra (final fantasy xi)',
        'deerstalker': 'deerstalker hat',
        'kigurumi': 'kigurumi (animal onesie)',
        'club_(shape)': 'club shape',
        'animal_bag': 'animal-shaped bag',
        'lace-trimmed_skirt': 'skirt with lace trim',
        'kimono_pull': 'pulling kimono',
        'kanabou': 'kanabou (spiked club)',
        'animal_hug': 'hugging animal',
        'sakuramon': 'sakuramon (unknown context)',
        'shinai': 'shinai (bamboo sword)',
        'nearly_naked_apron': 'nearly naked with apron',
        'naked_bandage': 'naked with bandage',
        '2009': 'year 2009',
        'papakha': 'papakha (russian hat)',
        'teruterubouzu': 'teruterubouzu (weather charm)',
        'gathers': 'gathers (fabric)',
        'ema': 'ema (votive tablet)',
        'neckwear_grab': 'grabbing neckwear',
        'newhalf': 'newhalf (transgender)',
        'load_bearing_vest': 'load-bearing vest',
        'lace-trimmed_gloves': 'gloves with lace trim',
        'tengu': 'tengu (japanese spirit)',
        'hands_on_ass': 'hands on butt',
        'honeycomb_(pattern)': 'honeycomb pattern',
        'riding_pokemon': 'riding pokémon',
        'knees_apart_feet_together': 'knees apart',
        'kesa': 'kesa (buddhist robe)',
        'bow_(music)': 'musical bow',
        'lalafell': 'lalafell (race)',
        'digitigrade': 'digitigrade legs',
        'bikesuit': 'bike suit',
        'uchikake': 'uchikake (bridal kimono)',
        'buruma_pull': 'pulling buruma',
        'fuuin_no_tsue': 'fuuin no tsue (sealed staff)',
        'toilet_use': 'using toilet',
        'shirt_grab': 'grabbing shirt',
        'ootachi': 'ootachi (large sword)',
        'ribbon-trimmed_dress': 'dress with ribbon trim',
        '3others': 'three others',
        'mouth_pull': 'pulling mouth',
        'legs_folded': 'folded legs',
        'liquid_hair': 'hair made of liquid',
        'heart_button': 'heart-shaped button',
        'ass_support': 'supporting butt',
        'decepticon': 'decepticon (transformers)',
        'strap_lift': 'lifting strap',
        'cheek_press': 'pressing cheek',
        '6+others': 'six or more others',
        'tanzaku': 'tanzaku (wish card)',
        'bow_legwear': 'legwear with bow',
        'covering_ass': 'covering butt',
        'bicorne': 'bicorne (two-cornered hat)',
        'c:': 'smiling face (c:)',
        'jimiko': 'jimiko (plain girl)',
        'hanetsuki': 'hanetsuki (japanese badminton)',
        'aestus_estus': 'aestus estus (fate)',
        'onbashira': 'onbashira (sacred pillar)',
        'tricorne': 'tricorne (three-cornered hat)',
        'taut_dress': 'tight dress',
        'choko_(cup)': 'choko (sake cup)',
        'heckler_&_koch': 'heckler & koch (firearms)',
        'ushanka': 'ushanka (russian hat)',
        'suppressor': 'suppressor (firearm)',
        'poke_ball_print': 'poké ball print',
        'hakurei_reimu_(cosplay)': 'hakurei reimu cosplay',
        'hagoita': 'hagoita (japanese paddle)',
        'staff_(music)': 'musical staff',
        'shikigami': 'shikigami (spirit)',
        'gem_(symbol)': 'gem symbol',
        'ramune': 'ramune (japanese soda)',
        'naked_hoodie': 'naked with hoodie',
        'kusazuri': 'kusazuri (armor skirt)',
        'circled_9': 'circled number 9',
        'clothed_female_nude_female': 'clothed female',
        'ribbon-trimmed_collar': 'collar with ribbon trim',
        'earth_(ornament)': 'earth ornament',
        'sanshoku_dango': 'sanshoku dango (three-color dumpling)',
        'yagasuri': 'yagasuri (arrow pattern)',
        'raimon': 'raimon (thunder)',
        'heart_tail': 'heart-shaped tail',
        'okamisty': 'okamisty (unknown context)',
        '2013': 'year 2013',
        'ass_cutout': 'butt cutout',
        'dirndl': 'dirndl (dress)',
        'omurice': 'omurice (omelet rice)',
        '2012': 'year 2012',
        'black_buruma': 'black buruma (gym shorts)',
        '2010': 'year 2010',
        'h&k_hk416': 'h&k hk416 (rifle)',
        'makizushi': 'makizushi (sushi roll)',
        'triforce': 'triforce (zelda)',
        'eyewear_on_headwear': 'glasses on headwear',
        'pectoral_grab': 'grabbing pectorals',
        'kanji': 'kanji (japanese character)',
        'sangvis_ferri': "sangvis ferri (girls' frontline)",
        'onmyouji': 'onmyouji (spiritualist)',
        'pom_pom_hair_ornament': 'pom-pom hair ornament',
        '39': 'number 39',
        'takoyaki': 'takoyaki (octopus balls)',
        'dakimakura_(object)': 'dakimakura (hug pillow)',
        'happi': 'happi (festival coat)',
        'forehead-to-forehead': 'forehead to forehead',
        'ajirogasa': 'ajirogasa (woven hat)',
        'naked_kimono': 'naked with kimono',
        'glomp': 'glomp (hug)',
        'sidepec': 'sidepec (unknown context)',
        'print_bra': 'printed bra',
        'nike': 'nike (brand)',
        '2011': 'year 2011',
        'hauchiwa': 'hauchiwa (fan)',
        'drawing_bow': 'drawing a bow',
        'carrying_person': 'carrying a person',
        'blowing_kiss': 'blowing a kiss',
        'lube': 'lubricant',
        'onee-loli': 'older girl with loli',
        'pokedex_number': 'pokédex number',
        'diagonal-striped_necktie': 'diagonally striped necktie',
        '._.': 'blank face',
        'tail_grab': 'grabbing tail',
        'bandaid_on_hand': 'bandage on hand',
        'lace-trimmed_sleeves': 'sleeves with lace trim',
        'mole_on_ass': 'mole on butt',
        'shortstack': 'shortstack (short and curvy)',
        'yordle': 'yordle (league of legends)',
        'nippleless_clothes': 'clothes without nipples',
        'tanuki': 'tanuki (raccoon dog)',
        'tegaki': 'tegaki (hand-drawn)',
        'child_on_child': 'child with child',
        'have_to_pee': 'needing to pee',
        'shuriken': 'shuriken (throwing star)',
        'covered_face': 'face covered',
        'crotch_rub': 'rubbing crotch',
        'pillow_grab': 'grabbing pillow',
        'afro': 'afro hairstyle',
        'taiyaki': 'taiyaki (fish-shaped cake)',
        'nengajou': "nengajou (new year's card)",
        'setsubun': 'setsubun (festival)',
        'three-dimensional_maneuver_gear': '3d maneuver gear',
        'tokkuri': 'tokkuri (sake bottle)',
        'boxers': 'boxer shorts',
        'hanfu': 'hanfu (chinese clothing)',
        'in_bucket': 'in a bucket',
        'cheek_pinching': 'pinching cheek',
        'shared_umbrella': 'sharing an umbrella',
        'hyur': 'hyur (race)',
        'head_back': 'head tilted back',
        'cheek_poking': 'poking cheek',
        'ribbon-trimmed_clothes': 'clothes with ribbon trim',
        'heart_hands_duo': 'heart hands (duo)',
        'harvin': 'harvin (race)',
        'naked_cape': 'naked with cape',
        'spear_the_gungnir': 'spear of gungnir',
        'akeome': "akeome (new year's greeting)",
        'sleeping_on_person': 'sleeping on another person',
        'bandaid_on_arm': 'bandage on arm',
        'breast_curtain': 'breasts covered by curtain',
        'cross_scar': 'cross-shaped scar',
        'shared_food': 'sharing food',
        'plectrum': 'plectrum (guitar pick)',
        'after_kiss': 'after a kiss',
        ':x': 'crossed face',
        'beltbra': 'bra with belt',
        'mask_pull': 'pulling mask',
        'doyagao': 'smug face (doyagao)',
        'naked_jacket': 'naked with jacket',
        'mace': 'mace (weapon)',
        'mimikaki': 'mimikaki (ear pick)',
        'pokemon_on_head': 'pokémon on head',
        'tanabata': 'tanabata (festival)',
        'x_x': 'dead face',
        'poke_ball_symbol': 'poké ball symbol',
        'seigaiha': 'seigaiha (wave pattern)',
        'tangzhuang': 'tangzhuang (chinese jacket)',
        'voyakiloid': 'voyakiloid (vocaloid variant)',
        'shinsengumi': 'shinsengumi (samurai group)',
        'jirai_kei': 'jirai kei (fashion style)',
        'autobot': 'autobot (transformers)',
        'dress_tug': 'tugging dress',
        'tokusatsu': 'tokusatsu (special effects)',
        'thighhighs_pull': 'pulling thighhighs',
        'breasts_on_glass': 'breasts pressed against glass',
        'pawpads': 'paw pads',
        'hikimayu': 'hikimayu (thin eyebrows)',
        'medium_dress': 'medium-length dress',
        'moon_(ornament)': 'moon ornament',
        'full_nelson': 'full nelson (wrestling)',
        'naginata': 'naginata (pole weapon)',
        'leotard_pull': 'pulling leotard',
        'viera': 'viera (race)',
        'claw_(weapon)': 'claw weapon',
        '2014': 'year 2014',
        'spade_(shape)': 'spade shape',
        'linea_alba': 'linea alba (abdominal line)',
        'heart_pillow': 'heart-shaped pillow',
        'holding_pom_poms': 'holding pom-poms',
        'eyepatch_bikini': 'bikini with eyepatch',
        '2018': 'year 2018',
        'mouth_drool': 'drooling mouth',
        'anime_coloring': 'anime-style coloring',
        '2019': 'year 2019',
        'come_hither': 'come hither gesture',
        '2016': 'year 2016',
        'prone_bone': 'prone bone position',
        'doll_hug': 'hugging a doll',
        'updo': 'updo hairstyle',
        'two-footed_footjob': 'footjob with both feet',
        'bow_bikini': 'bikini with bow',
        'shouji': 'shouji (sliding door)',
        '2015': 'year 2015',
        'bandaid_on_cheek': 'bandage on cheek',
        'female_pov': 'female point of view',
        'hadanugi_dousa': 'hadanugi dousa (undressing motion)',
        'o3o': 'surprised face (o3o)',
        '2017': 'year 2017',
        ':i': 'neutral face',
        "tam_o'_shanter": "tam o' shanter (cap)",
        'd-pad': 'd-pad (controller)',
        'diagonal-striped_bow': 'diagonally striped bow',
        'mouse_(computer)': 'computer mouse',
        'enpera': 'enpera (unknown context)',
        'covered_abs': 'abs covered',
        'shimakaze_(kancolle)_(cosplay)': 'shimakaze (kancolle) cosplay',
        'tri_tails': 'three tails',
        '??': 'unknown',
        'octarian': 'octarian (splatoon)',
        'kabedon': 'kabedon (wall slam)',
        'starter_pokemon_trio': 'starter pokémon trio',
        'curtain_grab': 'grabbing curtain',
        'keyboard_(instrument)': 'keyboard (musical instrument)',
        'bolt_action': 'bolt action (firearm)',
        'mega_pokemon': 'mega pokémon',
        'naked_coat': 'naked with coat',
        'flower_(symbol)': 'flower symbol',
        ';3': 'cat face',
        '>_o': 'winking face',
        'mini-hakkero': 'mini-hakkero (touhou)',
        'head_grab': 'grabbing head',
        'clothes_down': 'clothes pulled down',
        'naked_sheet': 'naked with sheet',
        'ribbon-trimmed_skirt': 'skirt with ribbon trim',
        'kappougi': 'kappougi (apron)',
        'policewoman': 'female police officer',
        'afloat': 'floating',
        'bandaids_on_nipples': 'bandages on nipples',
        'hairpods': 'hairpods (hair accessories)',
        'print_bowtie': 'printed bowtie',
        'covered_collarbone': 'collarbone covered',
        'footwear_bow': 'bow on footwear',
        'rudder_footwear': 'rudder-shaped footwear',
        'flashing': 'flashing (exposing)',
        'holding_pokemon': 'holding pokémon',
        'tomoe_(symbol)': 'tomoe symbol',
        'taur': 'centaur or tauric body',
        'dress_bow': 'bow on dress',
        'gloved_handjob': 'handjob with glove',
        'furisode': 'furisode (long-sleeved kimono)',
        'multiple_crossover': 'multiple crossovers',
        'horn_bow': 'horn-shaped bow',
        'baozi': 'baozi (steamed bun)',
        'finger_gun': 'finger gun gesture',
        'pumps': 'pumps (shoes)',
        'lip_biting': 'biting lip',
        'bad_feet': 'unusual feet',
        'reverse_bunnysuit': 'reverse bunny suit',
        "grabbing_another's_ass": "grabbing another's butt",
        'obiage': 'obiage (kimono sash)',
        'w_arms': 'w-shaped arms',
        'lying_on_person': 'lying on another person',
        'leotard_aside': 'leotard pulled aside',
        'piggyback': 'piggyback ride',
        'clothes_grab': 'grabbing clothes',
        'hair_twirling': 'twirling hair',
        'single_kneehigh': 'single kneehigh sock',
        'obliques': 'oblique muscles',
        'midair': 'in midair',
        'egasumi': 'egasumi (japanese pattern)',
        'pubic_hair_peek': 'peeking pubic hair',
        'lifting_person': 'lifting a person',
        'shikishi': 'shikishi (art board)',
        'miniboy': 'small boy',
        'clothed_pokemon': 'clothed pokémon',
        'gloom_(expression)': 'gloomy expression',
        'shirt_tug': 'tugging shirt',
        'guro': 'guro (gore art)',
        'in_box': 'in a box',
        'kanzashi': 'kanzashi (hairpin)',
        '2020': 'year 2020',
        'in_tree': 'in a tree',
        'hagoromo': 'hagoromo (feathered robe)',
        'crotch_rope': 'rope around crotch',
        '5koma': '5-panel comic',
        'peeing_self': 'peeing oneself',
        'mochi': 'mochi (rice cake)',
        'au_ra': 'au ra (race)',
        'kote': 'kote (armored sleeves)',
        'quad_tails': 'four tails',
        'earclip': 'ear clip',
        'breast_curtains': 'breasts covered by curtains',
        'flats': 'flats (shoes)',
        'yugake': 'yugake (archery glove)',
        'breastless_clothes': 'clothes without breast coverage',
        'chest_sarashi': 'chest sarashi (bandage)',
        'shoe_dangle': 'shoe dangling',
        'bento': 'bento (lunch box)',
        'shoulder_carry': 'carrying on shoulder',
        'paw_shoes': 'paw-shaped shoes',
        'yunomi': 'yunomi (tea cup)',
        'qing_guanmao': 'qing guanmao (hat)',
        'kyuubi': 'kyuubi (nine-tailed fox)',
        'kogal': 'kogal (schoolgirl style)',
        'flat_ass': 'flat butt',
        'wa_maid': 'japanese-style maid',
        'bullpup': 'bullpup (firearm)',
        'wide_spread_legs': 'legs spread wide',
        'skirt_tug': 'tugging skirt',
        'kitsune': 'kitsune (fox spirit)',
        'knees_to_chest': 'knees pulled to chest',
        'strap_pull': 'pulling a strap',
        'multiple_4koma': 'multiple 4-panel comics',
        'naked_ribbon': 'naked with ribbon',
        'holding_ball': 'holding a ball',
        'mixed_bathing': 'mixed-gender bathing',
        'holding_can': 'holding a can',
        'navel_hair': 'belly button hair',
        'shushing': 'shushing gesture',
        'one-piece_swimsuit_pull': 'pulling a one-piece swimsuit',
        'blunt_ends': 'blunt hair ends',
        'aiguillette': 'aiguillette (decorative cord)',
        'reverse_trap': 'reverse trap (female passing as male)',
        'heart_pasties': 'heart-shaped pasties',
        'pillow_hat': 'pillow as hat',
        'ringlets': 'hair ringlets',
        'bandaid_on_nose': 'bandage on nose',
        'holding_strap': 'holding a strap',
        'grabbing_own_ass': 'grabbing own butt',
        'lowleg_bikini': 'low-leg bikini',
        'maebari': 'maebari (modesty patch)',
        '>:(': 'angry face',
        'print_skirt': 'printed skirt',
        'thigh_grab': 'grabbing thigh',
        'red_buruma': 'red buruma (gym shorts)',
        'medium_skirt': 'medium-length skirt',
        'bodypaint': 'body paint',
        'dress_pull': 'pulling dress',
        'ribbon-trimmed_legwear': 'legwear with ribbon trim',
        'bikini_bottom_aside': 'bikini bottom pulled aside',
        '1koma': '1-panel comic',
        'taking_picture': 'taking a picture',
        'kiseru': 'kiseru (japanese pipe)',
        'bikini_tan': 'bikini tan lines',
        'blue_buruma': 'blue buruma (gym shorts)',
        'backboob': 'side breast (backboob)',
        'obijime': 'obijime (kimono cord)',
        'spoken_blush': 'blushing (spoken)',
        'print_bow': 'printed bow',
        '1980s_(style)': '1980s style',
        'uchiwa': 'uchiwa (japanese fan)',
        'bubble_blowing': 'blowing bubbles',
        ':>=': 'smug face',
        'bandaid_on_knee': 'bandage on knee',
        '2021': 'year 2021',
        'lamia': 'lamia (snake person)',
        'fisheye': 'fisheye view',
        '2others': 'two others',
        'zouri': 'zouri (japanese sandals)',
        'sode': 'sode (shoulder armor)',
        'cheek-to-cheek': 'cheek to cheek',
        'spread_ass': 'spread buttocks',
        '2022': 'year 2022',
        'pince-nez': 'pince-nez glasses',
        'v-fin': 'v-fin (robot crest)',
        'shide': 'shide (zigzag paper streamer)',
        'netorare': 'netorare (cuckoldry)',
        'bikini_lift': 'lifting bikini',
        'horror_(theme)': 'horror theme',
        'kunai': 'kunai (throwing knife)',
        'rei_no_himo': 'rei no himo (ceremonial cord)',
        'what': 'what?',
        'kissing_cheek': 'kissing on the cheek',
        'leaning_on_person': 'leaning on another person',
        'print_gloves': 'printed gloves',
        'keyboard_(computer)': 'computer keyboard',
        ';q': 'winking with tongue out',
        'swimsuit_aside': 'swimsuit pulled aside',
        'pompadour': 'pompadour hairstyle',
        'print_dress': 'printed dress',
        'hair_tucking': 'tucking hair',
        'shiny_pokemon': 'shiny pokémon',
        'naked_sweater': 'naked in sweater',
        'oppai_loli': 'small girl with large breasts',
        'pantylines': 'panty lines',
        'sheet_grab': 'grabbing sheet',
        'short_over_long_sleeves': 'short sleeves over long sleeves',
        '1990s_(style)': '1990s style',
        'fat': 'overweight',
        'print_bikini': 'printed bikini',
        ':/': 'uncertain face',
        'pink_thighhighs': 'pink thigh-high socks',
        'd:': 'sad face',
        'karakasa_obake': 'karakasa-obake (umbrella ghost)',
        "miqo'te": "mi'qote (final fantasy race)",
        'lowleg_panties': 'low-leg panties',
        'print_panties': 'printed panties',
        'jiangshi': 'jiangshi (chinese hopping vampire)',
        'fishnet_thighhighs': 'fishnet thigh-high socks',
        'torogao': 'melting face (torogao)',
        'zzz': 'sleeping (zzz)',
        '3:': 'cat face (3:)',
        'faulds': 'faulds (armor)',
        'clothed_male_nude_female': 'clothed male',
        'shirt_pull': 'shirt pulled',
        'uwabaki': 'uwabaki (japanese school shoes)',
        'kariginu': 'kariginu (japanese robe)',
        'huge_ahoge': 'large ahoge (hair antenna)',
        'torso_grab': 'grabbing torso',
        'pillow_hug': 'hugging pillow',
        'nekomata': 'nekomata (two-tailed cat)',
        'bandaid_on_leg': 'band-aid on leg',
        'fat_mons': 'large monster (fat mons)',
        'xd': 'laughing face (xd)',
        'over-kneehighs': 'over-knee-high socks',
        'bra_pull': 'bra being pulled',
        'kotatsu': 'kotatsu (heated table)',
        'onee-shota': 'older girl',
        'expressions': 'facial expressions',
        'grey_thighhighs': 'grey thigh-high socks',
        ':|': 'neutral face',
        'stand_(jojo)': "stand (jojo's bizarre adventure)",
        '=3': 'cat face (=3)',
        'sweater_lift': 'sweater lifted',
        'book_stack': 'stack of books',
        'thighhighs_under_boots': 'thigh-high socks under boots',
        'vertical-striped_thighhighs': 'vertical-striped thigh-high socks',
        ';p': 'winking tongue face',
        'hand_on_own_ass': 'hand on own buttocks',
        'frilled_thighhighs': 'frilled thigh-high socks',
        'tengu-geta': 'tengu-geta (japanese clogs)',
        'dango': 'dango (japanese dumpling)',
        'colored_tips': 'colored hair tips',
        'danmaku': 'danmaku (bullet hell)',
        'yandere': 'yandere (obsessive love)',
        'breast_suppress': 'breast suppression',
        'shorts_pull': 'shorts being pulled',
        'sanpaku': 'sanpaku eyes',
        'dougi': 'dougi (martial arts uniform)',
        'onigiri': 'onigiri (rice ball)',
        'turn_pale': 'turning pale',
        'heart_ahoge': 'heart-shaped ahoge',
        'side-by-side': 'side by side',
        'lying': 'lying down',
        'serafuku': 'japanese school uniform',
        'hairclip': 'hair clip',
        'black_thighhighs': 'black thigh-high socks',
        '3girls': 'three women',
        '2boys': 'men',
        'on_back': 'lying on back',
        'off_shoulder': 'off-shoulder',
        'clothes_lift': 'clothes lifted',
        'yuri': 'lesbian (yuri)',
        'huge_breasts': 'very large breasts',
        ':o': 'surprised face',
        'from_side': 'from the side',
        'white_thighhighs': 'white thigh-high socks',
        'zettai_ryouiki': 'zettai ryouiki (absolute territory)',
        'kneehighs': 'knee-high socks',
        'loli': 'lolita (loli)',
        'v': 'v shape',
        '4girls': 'four women',
        '4koma': '4-panel comic (4koma)',
        ':3': 'cat face',
        '^_^': 'happy face',
        'pov': 'point of view (pov)',
        '6+girls': 'six or more girls',
        'low_twintails': 'low twin tails',
        'highleg': 'high-leg',
        'ass_visible_through_thighs': 'buttocks visible through thighs',
        'wariza': 'japanese sitting style (wariza)',
        'mouth_hold': 'holding in mouth',
        'shirt_lift': 'shirt lifted',
        'obi': 'obi (sash)',
        'clothes_pull': 'clothes pulled',
        'pantyshot': 'panty shot',
        'eyepatch': 'eye patch',
        'skirt_lift': 'skirt lifted',
        'abs': 'abdominal muscles',
        ';d': 'winking smile',
        '3boys': 'three men',
        'aged_down': 'younger appearance (aged down)',
        'breasts_out': 'breasts exposed',
        '5girls': 'five women',
        'pectorals': 'pectoral muscles',
        'x_hair_ornament': 'x-shaped hair ornament',
        'on_stomach': 'lying on stomach',
        '>_<': 'frustrated face',
        'short_twintails': 'short twin tails',
        'all_fours': 'on all fours',
        '^^^': 'excited face',
        '?': 'question mark',
        'panty_pull': 'panties being pulled',
        'otoko_no_ko': 'otoko no ko (feminine boy)',
        'single_thighhigh': 'single thigh-high sock',
        'fishnets': 'fishnet stockings',
        'genderswap': 'gender swap',
        'bandaid': 'band-aid',
        'bara': 'muscular man (bara)',
        '1girl': 'woman',
        'looking_at_viewer': 'looking at the camera',
        'thighhighs': 'thigh-high socks',
        '1boy': 'man',
        '2girls': 'two women',
        'twintails': 'twin tails',
        'ass': 'buttocks',
        'ahoge': 'single hair strand sticking up',
        ':d': 'big smile',
        'original_tag': 'natural_translation',
        'no_headwear': 'no headwear present',
        'clothes_writing': 'writing or text on clothing',
        'jingle_bell': 'jingle bell accessory',
        'baseball_cap': 'baseball cap worn',
        'hair_flaps': 'hair flaps visible',
        'string_bikini': 'string bikini outfit',
        'hooded_jacket': 'jacket with a hood',
        'bikini_top_only': 'wearing only a bikini top',
        'twin_drills': 'twin drill hairstyle',
        'facing_viewer': 'facing the viewer',
        'skin_tight': 'skin-tight clothing',
        'red_nails': 'red painted nails',
        'web_address': 'web address visible',
        'angry': 'angry expression',
        'cloak': 'wearing a cloak',
        'eyewear_on_head': 'glasses on head',
        'motor_vehicle': 'motor vehicle present',
        'claws': 'claws visible',
        'side_braid': 'side braid hairstyle',
        'carrying': 'carrying something',
        'smartphone': 'smartphone visible',
        'corset': 'wearing a corset',
        'tentacles': 'tentacles present',
        'clothing_aside': 'clothing pushed aside',
        'rifle': 'rifle present',
        'mary_janes': 'mary jane shoes',
        'tareme': 'tareme (droopy eyes)',
        'neck_bell': 'bell on neck',
        'furry': 'furry character',
        'strap_slip': 'strap slipping',
        'pom_pom_(clothes)': 'pom-pom on clothes',
        'french_braid': 'french braid hairstyle',
        'close-up': 'close-up view',
        'androgynous': 'androgynous appearance',
        '1other': 'one other person',
        'forehead': 'forehead visible',
        'tsurime': 'tsurime (sharp eyes)',
        'seiza': 'seiza sitting',
        'upskirt': 'upskirt view',
        'pink_nails': 'pink painted nails',
        'genderswap_(mtf)': 'male to female genderswap',
        'wading': 'wading in water',
        'faceless': 'faceless character',
        'highleg_leotard': 'high-leg leotard',
        'spoken_heart': 'spoken heart symbol',
        'curvy': 'curvy figure',
        'breast_hold': 'holding breasts',
        'dress_lift': 'lifting dress',
        'halloween': 'halloween theme',
        'half_updo': 'half updo hairstyle',
        'blue_nails': 'blue painted nails',
        'holding_book': 'holding a book',
        'large_pectorals': 'large pectoral muscles',
        'clothed_female_nude_male': 'clothed female',
        '6+boys': 'six or more boys',
        'ribbon-trimmed_sleeves': 'sleeves with ribbon trim',
        'holding_phone': 'holding a phone',
        'contrapposto': 'contrapposto pose',
        'meme': 'internet meme',
        'toenails': 'painted toenails',
        'toned': 'toned body',
        'doggystyle': 'doggystyle position',
        '4boys': 'four men',
        'buruma': 'buruma (gym shorts)',
        'jitome': 'jitome (narrow eyes)',
        'v_arms': 'v-shaped arms',
        'ass_grab': 'grabbing butt',
        'head_rest': 'head resting',
        'poke_ball': 'poké ball',
        'minigirl': 'miniature girl',
        'plump': 'plump body',
        'sarashi': 'sarashi (cloth wrap)',
        'knees_together_feet_apart': 'knees together',
        'sheathed': 'sheathed weapon',
        'yukata': 'yukata (summer kimono)',
        'bow_(weapon)': 'bow weapon',
        'oni': 'oni (demon)',
        'serious': 'serious expression',
        'missionary': 'missionary position',
        'wide-eyed': 'wide-eyed expression',
        'dakimakura_(medium)': 'dakimakura (hug pillow)',
        'contemporary': 'contemporary style',
        'ofuda': 'ofuda (paper charm)',
        'object_hug': 'hugging an object',
        'oekaki': 'oekaki (sketch)',
        'valentine': "valentine's theme",
        'enmaided': 'enmaided (maid transformation)',
        'miko': 'miko (shrine maiden)',
        'panties_aside': 'panties pushed aside',
        'pout': 'pouting',
        'hair_bell': 'bell in hair',
        'forehead_mark': 'mark on forehead',
        'realistic': 'photo',
        'skirt_hold': 'holding skirt',
        'fantasy': 'fantasy theme',
        'hime_cut': 'hime cut hairstyle',
        'on_floor': 'on the floor',
        'eighth_note': 'eighth note symbol',
        'geta': 'geta (japanese sandals)',
        'top-down_bottom-up': 'top-down bottom-up view',
        'sitting_on_person': 'sitting on a person',
        'arrow_(symbol)': 'arrow symbol',
        'double_v': 'double v gesture',
        'spread_arms': 'arms spread',
        'labcoat': 'lab coat',
        'yokozuwari': 'yokozuwari (kneeling pose)',
        'shota': 'shota (young boy)',
        'lowleg': 'low-leg clothing',
        'bandeau': 'bandeau top',
        'highleg_panties': 'high-leg panties',
        'gothic_lolita': 'gothic lolita fashion',
        'ass_focus': 'butt focus',
        'beanie': 'beanie hat',
        'wince': 'wincing expression',
        'hat_flower': 'flower on hat',
        'hitodama': 'hitodama (spirit flame)',
        'ahegao': 'ahegao (exaggerated face)',
        'purple_nails': 'purple painted nails',
        'tabi': 'tabi (japanese socks)',
        'back-to-back': 'back-to-back pose',
        'gakuran': 'gakuran (school uniform)',
        'pocky': 'pocky snack',
        'argyle': 'argyle pattern',
        'covered_mouth': 'mouth covered',
        'shrug_(clothing)': 'shrug clothing',
        'holding_flower': 'holding a flower',
        'onsen': 'onsen (hot spring)',
        'vambraces': 'vambraces (arm guards)',
        '2koma': 'two-panel comic',
        'gohei': 'gohei (ritual wand)',
        'highleg_swimsuit': 'high-leg swimsuit',
        'retro_artstyle': 'retro art style',
        'arm_grab': 'grabbing arm',
        'wind_lift': 'wind lifting',
        'poke_ball_(basic)': 'basic poké ball',
        'double-breasted': 'double-breasted clothing',
        'smug': 'smug expression',
        'chestnut_mouth': 'chestnut-shaped mouth',
        'muneate': 'muneate (breastplate)',
        'holding_knife': 'holding a knife',
        'pom_pom_(cheerleading)': 'pom-pom for cheerleading',
        'beachball': 'beach ball',
        'foot_focus': 'focus on feet',
        'holding_poke_ball': 'holding a poké ball',
        'nipple_tweak': 'tweaking nipple',
        'back_bow': 'bow on back',
        'tatami': 'tatami mat',
        'mecha_musume': 'mecha musume (mecha girl)',
        'toeless_legwear': 'legwear without toes',
        'naked_shirt': 'naked with shirt',
        'bow_bra': 'bra with bow',
        'triangle_mouth': 'triangle-shaped mouth',
        'print_kimono': 'printed kimono',
        '5boys': 'five boys',
        'randoseru': 'randoseru (japanese backpack)',
        'heart_hands': 'heart hands gesture',
        'heart_of_string': 'heart made of string',
        'against_wall': 'against a wall',
        'own_hands_clasped': 'hands clasped together',
        'print_legwear': 'printed legwear',
        'holding_bag': 'holding a bag',
        'one_breast_out': 'one breast exposed',
        'holding_bottle': 'holding a bottle',
        'lace-trimmed_legwear': 'legwear with lace trim',
        'cone_hair_bun': 'cone-shaped hair bun',
        'hibiscus': 'hibiscus flower',
        'tate_eboshi': 'tate eboshi (japanese hat)',
        'habit': "habit (nun's attire)",
        'facepaint': 'face paint',
        'holding_fan': 'holding a fan',
        'torii': 'torii (shrine gate)',
        'haori': 'haori (kimono jacket)',
        'tasuki': 'tasuki (sash)',
        'holding_tray': 'holding a tray',
        'tight': 'tight clothing',
        'magatama': 'magatama (bead)',
        'lace-trimmed_panties': 'panties with lace trim',
        'highleg_bikini': 'high-leg bikini',
        'tied_shirt': 'shirt tied at waist',
        'garrison_cap': 'garrison cap (military hat)',
        'midriff_peek': 'midriff showing',
        'one-piece_tan': 'tan lines from one-piece swimsuit',
        'giant': 'giant (very large person)',
        'crescent_hat_ornament': 'crescent-shaped hat ornament',
        'leg_ribbon': 'ribbon on leg',
        'looking_afar': 'looking into the distance',
        'presenting': 'presenting (showing something)',
        'princess_carry': 'carrying someone princess-style',
        'pantyhose_pull': 'pulling pantyhose',
        'shoulder_blades': 'shoulder blades visible',
        'deep_skin': 'deep skin tone',
        'draph': 'draph (fantasy race)',
        'over_shoulder': 'over the shoulder',
        'one_knee': 'on one knee',
        'w': 'w (expression)',
        'huge_ass': 'large buttocks',
        'graphite_(medium)': 'graphite (drawing medium)',
        'hat_feather': 'feather on hat',
        'pigeon-toed': 'pigeon-toed stance',
        'lace-trimmed_bra': 'bra with lace trim',
        'naked_towel': 'naked with towel',
        'star_earrings': 'star-shaped earrings',
        'ringed_eyes': 'eyes with rings',
        'limited_palette': 'limited color palette',
        'on_couch': 'on a couch',
        'holding_microphone': 'holding a microphone',
        'shimenawa': 'shimenawa (sacred rope)',
        'animification': 'turned into an animal',
        'in_container': 'inside a container',
        'photo_(object)': 'photograph (object)',
        'greaves': 'greaves (leg armor)',
        'gap_(touhou)': 'gap (touhou character)',
        'leg_grab': 'grabbing leg',
        'bound_arms': 'arms bound',
        'out-of-frame_censoring': 'censoring out of frame',
        'lineart': 'line art',
        'multiple_persona': 'multiple personas',
        'undercut': 'undercut hairstyle',
        'polka_dot_bow': 'bow with polka dots',
        'halftone': 'halftone pattern',
        'naked_apron': 'naked with apron',
        'print_shirt': 'printed shirt',
        'pubic_tattoo': 'tattoo on pubic area',
        'bra_lift': 'lifting bra',
        '^o^': 'happy face (^o^)',
        'skirt_pull': 'pulling skirt',
        '3koma': 'three-panel comic',
        'eyewear_removed': 'glasses removed',
        'genderswap_(ftm)': 'female-to-male genderswap',
        'erune': 'erune (fantasy race)',
        'face-to-face': 'face to face',
        'ranguage': 'ranguage (unknown context)',
        'pants_pull': 'pulling pants',
        'bikini_pull': 'pulling bikini',
        'hachimaki': 'hachimaki (headband)',
        'tiptoes': 'standing on tiptoes',
        'babydoll': 'babydoll (lingerie)',
        'sakazuki': 'sakazuki (sake cup)',
        'cutoffs': 'cutoff shorts',
        'yukkuri_shiteitte_ne': 'yukkuri shiteitte ne (take it easy)',
        'fur-trimmed_sleeves': 'sleeves with fur trim',
        'm_legs': 'm-shaped legs',
        'fundoshi': 'fundoshi (japanese underwear)',
        '0_0': 'surprised face (0_0)',
        'on_ground': 'on the ground',
        'covered_eyes': 'eyes covered',
        'star_hat_ornament': 'star-shaped hat ornament',
        'body_writing': 'writing on body',
        'bishounen': 'bishounen (pretty boy)',
        ';o': 'winking face (;o)',
        'broom_riding': 'riding a broom',
        'breast_rest': 'breasts resting',
        'straight-on': 'straight-on view',
        'arm_ribbon': 'ribbon on arm',
        'yin_yang': 'yin-yang',
        'gyaru': 'gyaru (fashion style)',
        'kimono_lift': 'lifting kimono',
        'apron_lift': 'lifting apron',
        'art_nouveau': 'art nouveau style',
        'wa_lolita': 'wa lolita (japanese style)',
        'star_pasties': 'star-shaped pasties',
        'arachne': 'arachne (mythical creature)',
        'p90': 'p90 (firearm)',
        'leash_pull': 'pulling leash',
        'bralines': 'bra lines',
        'panty_lift': 'lifting panties',
        'wataboushi': 'wataboushi (bridal hat)',
        'animal_ear_headwear': 'headwear with animal ears',
        'breast_poke': 'poking breast',
        'baton_(conducting)': 'conducting baton',
        'kotoyoro': 'kotoyoro (unknown context)',
        'string_bra': 'bra with strings',
        'skirt_flip': 'flipping skirt',
        'chi-hatan_military_uniform': 'chi-ha-tan military uniform',
        'training_corps_(emblem)': 'training corps emblem',
        'naked_tabard': 'naked with tabard',
        'yurigaoka_girls_academy_school_uniform': "yurigaoka girls' academy school uniform",
        'stole': 'stole (scarf)',
        'kikumon': 'kikumon (chrysanthemum crest)',
        'pectoral_press': 'pressing pectorals',
        'riyo_(lyomsnpmp)_(style)': 'riyo (lyomsnpmp) style',
        'eyepatch_removed': 'eye patch removed',
        'ganguro': 'ganguro (fashion style)',
        'maneki-neko': 'maneki-neko (beckoning cat)',
        'nejiri_hachimaki': 'nejiri hachimaki (twisted headband)',
        'okobo': 'okobo (japanese footwear)',
        'kinchaku': 'kinchaku (drawstring bag)',
        'sideways_hat': 'hat worn sideways',
        'ehoumaki': 'ehoumaki (sushi roll)',
        'jacket_pull': 'pulling jacket',
        '2008': 'year 2008',
        'print_necktie': 'printed necktie',
        'beltskirt': 'belt skirt',
        'kappa': 'kappa (mythical creature)',
        'boxcutter': 'box cutter',
        'joy-con': 'joy-con (game controller)',
        'clothes_tug': 'tugging clothes',
        'legband': 'leg band',
        'zora': 'zora (legend of zelda)',
        'cheek_pull': 'pulling cheek',
        'lipgloss': 'lip gloss',
        'omikuji': 'omikuji (fortune slip)',
        'print_sarong': 'printed sarong',
        '2007': 'year 2007',
        'berry_(pokemon)': 'berry (pokémon)',
        'zeon': 'zeon (mobile suit gundam)',
        'sayagata': 'sayagata (pattern)',
        'holomyth': 'holomyth (hololive)',
        'jingasa': 'jingasa (war hat)',
        'ankle_grab': 'grabbing ankle',
        'sleeve_grab': 'grabbing sleeve',
        'book_hug': 'hugging book',
        'print_mug': 'printed mug',
        'oonusa': 'oonusa (shinto wand)',
        'sock_pull': 'pulling sock',
        'lowleg_skirt': 'low-leg skirt',
        'glove_biting': 'biting glove',
        'naked_cloak': 'naked with cloak',
        'ooarai_(emblem)': 'ooarai emblem',
        'kyuudou': 'kyūdō (japanese archery)',
        'ribbon-trimmed_headwear': 'headwear with ribbon trim',
        'kurokote': 'kurokote (unknown context)',
        'homu': 'homu (unknown context)',
        'hair_lift': 'lifting hair',
        'self_hug': 'hugging oneself',
        'fingersmile': 'smiling with fingers',
        'koi': 'koi fish',
        'cast': 'cast (medical)',
        'masu': 'masu (sake cup)',
        'h&k_ump': 'h&k ump (firearm)',
        'yamakasa': 'yamakasa (festival)',
        'behind-the-head_headphones': 'headphones behind head',
        'bokura_wa_ima_no_naka_de': 'bokura wa ima no naka de (song)',
        'igote': 'igote (unknown context)',
        'shamoji': 'shamoji (rice paddle)',
        'scylla': 'scylla (mythical creature)',
        'hoodie_lift': 'lifting hoodie',
        'cyrillic': 'cyrillic (alphabet)',
        'chikan': 'chikan (groper)',
        'ak-47': 'ak-47 (firearm)',
        'print_sleeves': 'printed sleeves',
        'beretta_92': 'beretta 92 (firearm)',
        'tamagoyaki': 'tamagoyaki (japanese omelette)',
        'wakamezake': 'wakamezake (sake with seaweed)',
        'teeth_hold': 'holding with teeth',
        'gibson_les_paul': 'gibson les paul (guitar)',
        'gesugao': 'gesugao (sinister face)',
        'red_(pokemon)': 'red (pokémon)',
        'rice_shower_(umamusume)': 'rice shower (uma musume)',
        'mejiro_mcqueen_(umamusume)': 'mejiro mcqueen (uma musume)',
        'selene_(pokemon)': 'selene (pokémon)',
        'daiwa_scarlet_(umamusume)': 'daiwa scarlet (uma musume)',
        'cynthia_(pokemon)': 'cynthia (pokémon)',
        'serena_(pokemon)': 'serena (pokémon)',
        'trainer_(umamusume)': 'trainer (uma musume)',
        'stocking_(psg)': 'stocking (panty & stocking)',
        'gold_ship_(umamusume)': 'gold ship (uma musume)',
        'misty_(pokemon)': 'misty (pokémon)',
        'tokai_teio_(umamusume)': 'tokai teio (uma musume)',
        'uraraka_ochako': 'urakaka ochako',
        'leon_(pokemon)': 'leon (pokémon)',
        'raihan_(pokemon)': 'raihan (pokémon)',
        'bea_(pokemon)': 'bea (pokémon)',
        'nessa_(pokemon)': 'nessa (pokémon)',
        'agnes_tachyon_(umamusume)': 'agnes tachyon (uma musume)',
        'louise_francoise_le_blanc_de_la_valliere': 'louise françoise le blanc de la vallière',
        'lana_(pokemon)': 'lana (pokémon)',
        'ethan_(pokemon)': 'ethan (pokémon)',
        'akari_(pokemon)': 'akari (pokémon)',
        'hilbert_(pokemon)': 'hilbert (pokémon)',
        'silence_suzuka_(umamusume)': 'silence suzuka (uma musume)',
        'panty_(psg)': 'panty (panty & stocking)',
        'hex_maniac_(pokemon)': 'hex maniac (pokémon)',
        'lyra_(pokemon)': 'lyra (pokémon)',
        'nice_nature_(umamusume)': 'nice nature (uma musume)',
        'mallow_(pokemon)': 'mallow (pokémon)',
        'brendan_(pokemon)': 'brendan (pokémon)',
        'sonia_(pokemon)': 'sonia (pokémon)',
        'iono_(pokemon)': 'iono (pokémon)',
        'manhattan_cafe_(umamusume)': 'manhattan cafe (uma musume)',
        'n_(pokemon)': 'n (pokémon)',
        'special_week_(umamusume)': 'special week (uma musume)',
        'leaf_(pokemon)': 'leaf (pokémon)',
        'lusamine_(pokemon)': 'lusamine (pokémon)',
        'symboli_rudolf_(umamusume)': 'symboli rudolf (uma musume)',
        'satono_diamond_(umamusume)': 'satono diamond (uma musume)',
        'skyla_(pokemon)': 'skyla (pokémon)',
        'oguri_cap_(umamusume)': 'oguri cap (uma musume)',
        'uiharu_kazari': 'uiha kazari',
        'mihono_bourbon_(umamusume)': 'mihono bourbon (uma musume)',
        'jessie_(pokemon)': 'jessie (pokémon)',
        'mayano_top_gun_(umamusume)': 'mayano top gun (uma musume)',
        'scathach_skadi_(fate)': 'scathach-skadi (fate)',
        'elesa_(pokemon)': 'elesa (pokémon)',
        'kris_(pokemon)': 'kris (pokémon)',
        'silver_(pokemon)': 'silver (pokémon)',
        'vodka_(umamusume)': 'vodka (uma musume)',
        'elio_(pokemon)': 'elio (pokémon)',
        'bianca_(pokemon)': 'bianca (pokémon)',
        'kitasan_black_(umamusume)': 'kitasan black (uma musume)',
        'piers_(pokemon)': 'piers (pokémon)',
        'hop_(pokemon)': 'hop (pokémon)',
        'eur asian_eagle_owl_(kemono_friends)': 'eurasian eagle owl (kemono friends)',
        'gladion_(pokemon)': 'gladion (pokémon)',
        'james_(pokemon)': 'james (pokémon)',
        'green_(pokemon)': 'green (pokémon)',
        'victor_(pokemon)': 'victor (pokémon)',
        'artoria_pendragon_(alter_swimsuit_rider)_(second_ascension)_(fate)': 'artoria pendragon (alter swimsuit rider',
        'haru_urara_(umamusume)': 'haru urara (uma musume)',
        'iris_(pokemon)': 'iris (pokémon)',
        'lucas_(pokemon)': 'lucas (pokémon)',
        'irida_(pokemon)': 'irida (pokémon)',
        'tamamo_cross_(umamusume)': 'tamamo cross (uma musume)',
        'sabrina_(pokemon)': 'sabrina (pokémon)',
        'eishin_flash_(umamusume)': 'eishin flash (uma musume)',
        'bede_(pokemon)': 'bede (pokémon)',
        'twin_turbo_(umamusume)': 'twin turbo (uma musume)',
        'nate_(pokemon)': 'nate (pokémon)',
        'meltryllis_(swimsuit_lancer)_(first_ascension)_(fate)': 'meltryllis (swimsuit lancer',
        'agnes_digital_(umamusume)': 'agnes digital (uma musume)',
        'seiun_sky_(umamusume)': 'seiun sky (uma musume)',
        'cheren_(pokemon)': 'cheren (pokémon)',
        'miyamoto_musashi_(swimsuit_berserker)_(second_ascension)_(fate)': 'miyamoto musashi (swimsuit berserker',
        'goh_(pokemon)': 'goh (pokémon)',
        'grass_wonder_(umamusume)': 'grass wonder (uma musume)',
        'lei_lei': 'lei-lei',
        'allister_(pokemon)': 'allister (pokémon)',
        'eva_02': 'eva-02',
        'curren_chan_(umamusume)': 'curren chan (uma musume)',
        'matikane_tannhauser_(umamusume)': 'matikane tannhauser (uma musume)',
        'air_groove_(umamusume)': 'air groove (uma musume)',
        'narita_brian_(umamusume)': 'narita brian (uma musume)',
        'hau_(pokemon)': 'hau (pokémon)',
        "jeanne_d'arc_alter_(avenger)_(third_ascension)_(fate)": "jeanne d'arc alter (avenger",
        'female_protagonist_(pokemon_go)': 'female protagonist (pokémon go)',
        'king_halo_(umamusume)': 'king halo (uma musume)',
        'calem_(pokemon)': 'calem (pokémon)',
        'eva_01': 'eva-01',
        'edmond_dantes_(fate)': 'edmond dantès (fate)',
        'guzma_(pokemon)': 'guzma (pokémon)',
        'narita_taishin_(umamusume)': 'narita taishin (uma musume)',
        'super_creek_(umamusume)': 'super creek (uma musume)',
        'acerola_(pokemon)': 'acerola (pokémon)',
        'bb_(swimsuit_mooncancer)_(second_ascension)_(fate)': 'bb (swimsuit mooncancer',
        'abigail_williams_(swimsuit_foreigner)_(third_ascension)_(fate)': 'abigail williams (swimsuit foreigner',
        'ingo_(pokemon)': 'ingo (pokémon)',
        'meisho_doto_(umamusume)': 'meisho doto (uma musume)',
        'meltryllis_(swimsuit_lancer)_(second_ascension)_(fate)': 'meltryllis (swimsuit lancer',
        "jeanne_d'arc_(swimsuit_archer)_(first_ascension)_(fate)": "jeanne d'arc (swimsuit archer",
        'fujimaru_ritsuka_(male)_(polar_chaldea_uniform)': 'fujimaru ritsuka (male',
        'erika_(pokemon)': 'erika (pokémon)',
        'lance_(pokemon)': 'lance (pokémon)',
        'mejiro_dober_(umamusume)': 'mejiro dober (uma musume)',
        'fine_motion_(umamusume)': 'fine motion (uma musume)',
        'admire_vega_(umamusume)': 'admire vega (uma musume)',
        'bb_(swimsuit_mooncancer)_(third_ascension)_(fate)': 'bb (swimsuit mooncancer',
        'smart_falcon_(umamusume)': 'smart falcon (uma musume)',
        'matikanefukukitaru_(umamusume)': 'matikanefukukitaru (uma musume)',
        'sweep_tosho_(umamusume)': 'sweep tosho (uma musume)',
        "jeanne_d'arc_(swimsuit_archer)_(second_ascension)_(fate)": "jeanne d'arc (swimsuit archer",
        'tail_around_leg': 'tail wrapped around leg',
        'hand_tattoo': 'tattoo on hand',
        'gao': 'gao (roar)',
        'hand_rest': 'hand resting',
        'wrist_bow': 'bow on wrist',
        'little_red_riding_hood_(grimm)_(cosplay)': 'little red riding hood (grimm) cosplay',
        'soft_serve': 'soft serve ice cream',
        'pov_doorway': 'pov from doorway',
        'flat_chest_grab': 'grabbing flat chest',
        'walther': 'walther (firearm)',
    }

    @classmethod
    def get_natural_tag(cls, tag):
        """Return the natural name for a tag using TAG_MAP, or sanitise if not found."""
        if tag in cls.TAG_MAP:
            return cls.TAG_MAP[tag]

        # Sanitise: replace underscores, strip, collapse spaces, and lowercase
        return " ".join(tag.replace("_", " ").strip().split()).lower()

