-- D1 schema for the telemetry ingestion Worker.
--
-- Two tables and nothing else. `install` holds one row per installation and no
-- request metadata: no IP, no user agent, no timestamps finer than a UTC date.
-- `aggregate_snapshot` holds the published numbers, computed daily and never
-- recomputed (see README, "compute daily, never backfill").

CREATE TABLE IF NOT EXISTS install (
  -- Canonical lowercase UUIDv4, generated by the client and validated here.
  install_id     TEXT    PRIMARY KEY,
  -- UTC dates, YYYY-MM-DD. Deliberately not timestamps: a precise first-seen
  -- instant is close to unique on its own.
  first_seen     TEXT    NOT NULL,
  last_seen      TEXT    NOT NULL,
  -- 63-bit rolling activity bitmap, relative to last_seen. Stored as a
  -- fixed-width `h`-prefixed hex string because D1's Workers API cannot bind
  -- BigInt and returns INTEGER as an imprecise JavaScript Number above 2^53.
  activity       TEXT    NOT NULL DEFAULT 'h0000000000000001',
  -- Sticky once a ping closes a >=14-day silence. This cannot be derived from
  -- the rolling bitmap forever because the gap eventually ages out.
  has_resurrected INTEGER NOT NULL DEFAULT 0,
  -- Write-once, from the first ping. Separates genuine new installs from the
  -- upgrade wave, which would otherwise make week-1 retention read absurdly
  -- high.
  is_new_install INTEGER NOT NULL DEFAULT 0,
  -- One of four coarse buckets. Docker installs ping daily and desktop/pip only
  -- when run, so the curve is uninterpretable without it.
  install_type   TEXT    NOT NULL
);

-- first_seen drives cohort bucketing; last_seen drives the retention prune.
CREATE INDEX IF NOT EXISTS idx_install_first_seen ON install (first_seen);
CREATE INDEX IF NOT EXISTS idx_install_last_seen  ON install (last_seen);

-- O(1) growth counters, so the insert path never runs COUNT(*) over the table
-- it is trying to protect. Two rows: `total_installs`, and `new_installs_today`
-- whose `day` is compared against the current UTC date before it is trusted.
CREATE TABLE IF NOT EXISTS counter (
  name  TEXT    PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0,
  day   TEXT
);

CREATE TABLE IF NOT EXISTS aggregate_snapshot (
  snapshot_date TEXT PRIMARY KEY,
  -- JSON blob of the day's published aggregate. Immutable once written: a
  -- cohort cell can only be computed while it is still inside the 63-day
  -- bitmap window, so it is stored the day it is computable and never derived
  -- again afterwards.
  payload       TEXT NOT NULL
);
