"""What a picture was generated by: the vault half of provenance (v1.11 Phase 2).

Provenance is three levels, because "how did I make this?" has three different
answers and collapsing them loses the one people actually ask for:

* A **recipe** is the topology: the graph and the assets it loads. Two images
  share a recipe when they came from the same workflow wired the same way,
  whatever the prompt or the seed.
* A **recipe instance** is the intent: prompt and scalar parameters on top of a
  recipe. Editing a prompt makes a new instance, never a new recipe.
* A :class:`Generation` is the event: one image, one seed. A re-roll is a new
  generation of the same instance.

**Only the third level lives here.** The first two are *hub* tables
(:mod:`pixlstash.hub.schema`, ``_V2_RECIPE_TABLES``), because a workflow is a
fact about the machine rather than about one library: measured on real
libraries, 70% of recipes appear in more than one, and a two-library comparison
found complete containment. Two libraries sharing a workflow is the norm, which
is the multi-library placement test answered directly. It is also what lets a
workflow outlive every picture that used it.

This module holds the half that names a ``picture.id`` and therefore cannot be
anything but vault-side: the generation event, and the resolution lock of what
each run consumed.

**The join between the halves is a hash, never an integer id.**
:attr:`Generation.instance_hash` carries the hub's ``recipe_instance.instance_hash``.
No foreign key can span the two databases, and SQLite hands a deleted row's id
to the next insert, so an integer link would silently re-point at a *different*
instance while still looking valid. Same rule, same reason, as
:mod:`pixlstash.db_models.adapter_attachment`.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlmodel import Field, SQLModel

# ``recipe.engine`` values. What produced the document, which decides how it is
# parsed and replayed. Declared here rather than in the hub module because the
# hub is stdlib sqlite3 with no model layer, and every consumer of these values
# already imports from ``db_models``.
ENGINE_COMFYUI = "comfyui"
ENGINE_AI_TOOLKIT = "ai-toolkit"

# ``recipe.hash_version`` / ``recipe_instance.hash_version`` values.
#
# ``v1`` is the canonicalization in the field-classification spec: an
# order-invariant label per node (Weisfeiler-Leman refinement), emitted as a
# sorted multiset of node descriptors, so a workflow rebuilt from scratch hashes
# identically to the original. ``v1-raw`` is the same rules with raw node ids,
# recorded when canonicalization could not run (a graph with a cycle through a
# reroute edge case). It is a separate value rather than a flag so the
# difference is visible in every query instead of silently grouping two
# incomparable hashes together.
HASH_VERSION_V1 = "v1"
HASH_VERSION_V1_RAW = "v1-raw"

# ``recipe_asset.asset_type`` values. ``unknown_model`` is what the unknown-node
# default rule produces from a widget whose value merely ends in a model
# extension: it is a real, expected state, not a parse failure.
ASSET_LORA = "lora"
ASSET_CHECKPOINT = "checkpoint"
ASSET_VAE = "vae"
ASSET_CLIP = "clip"
ASSET_CONTROLNET = "controlnet"
ASSET_UPSCALE_MODEL = "upscale_model"
ASSET_EMBEDDING = "embedding"
ASSET_IMAGE = "image"
ASSET_SNAPSHOT = "snapshot"
ASSET_UNKNOWN_MODEL = "unknown_model"


class Generation(SQLModel, table=True):
    """One image, produced by one instance, at one seed. **It outlives the image.**

    This is the row that makes "delete the pixels, keep the ability to recreate
    them" true, so its delete behaviour is the load-bearing decision here.

    ``image_id`` is nulled rather than cascaded when the picture goes. An
    earlier draft cascaded it, on the reasoning that the row describes one
    picture and says nothing without it. That was exactly backwards: the recipe
    and the instance are hub-side and survive regardless, but the **seed lives
    here**, so cascading meant deleting an image destroyed the last piece needed
    to reproduce it while leaving the workflow standing and apparently intact.
    Recipe plus instance plus seed is the whole recreation, and losing a third
    of it silently is worse than losing all of it.

    What is left after the picture is deleted is a **ghost**: the recipe (the
    core workflow), the instance (the diff off it), the seed, and
    ``image_sha256`` naming what used to be there. That is a few dozen bytes per
    deleted image against megabytes of pixels.

    **Permanent forget deletes this row, and leaves the recipe alone.** A recipe
    is a graph of node types and settings and is not personal data; a prompt and
    a thumbnail can be. That split is the whole reason the retention story can
    be honest: forgetting an image never costs the workflow, and keeping a
    workflow never keeps anything about the person in the picture.

    There is deliberately no unique constraint on ``image_id``. Ingest looks the
    image up before inserting, and a constraint here would turn a re-ingest race
    into an exception raised inside a background task, which is the failure mode
    the model-shelf work already learned to avoid. Nullability makes the point
    moot in the other direction too: many ghosts share a NULL ``image_id``.

    Attributes:
        image_id: The live picture, or NULL once it is gone. Never the identity.
        image_sha256: What the image was. Survives the picture, and is how a
            ghost is recognised if the same file comes back.
        instance_hash: The hub's ``recipe_instance.instance_hash``. A hash and
            not an integer, because this link crosses databases; see the module
            docstring.
        seed: The one genuinely volatile value. A re-roll is a new row here and
            changes nothing above it.
        overrides: JSON for rare last-mile deviations that never made it into
            the document.
        remote_job_id: Set when the image came back from an offloaded run. No
            foreign key: ``remote_job`` is Phase 5 and does not exist yet.
    """

    __tablename__ = "generation"

    id: Optional[int] = Field(default=None, primary_key=True)
    image_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            "image_id",
            Integer,
            ForeignKey("picture.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
    )
    image_sha256: Optional[str] = Field(
        default=None,
        sa_column=Column("image_sha256", String, nullable=True, index=True),
    )
    instance_hash: str = Field(
        sa_column=Column("instance_hash", String, nullable=False, index=True)
    )
    seed: Optional[int] = Field(
        default=None, sa_column=Column("seed", Integer, nullable=True)
    )
    overrides: Optional[str] = Field(
        default=None, sa_column=Column("overrides", String, nullable=True)
    )
    remote_job_id: Optional[int] = Field(
        default=None, sa_column=Column("remote_job_id", Integer, nullable=True)
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column("created_at", DateTime, nullable=False),
    )


class GenerationInput(SQLModel, table=True):
    """The resolution lock: which images a query-based node actually loaded.

    The PixlStash browse and search nodes select from vault state at run time,
    so the same workflow replayed next month loads different pictures. The
    workflow holds the query (the intent); this table holds what came back (the
    fact). Replay then has two honest modes: re-run the query for fresh results,
    or replay the lock for the exact images.

    A generation saved outside Picture Saver simply has no rows here, and that
    degrades to "query known, results unknown" rather than to a false claim of
    exact reproducibility.

    ``image_sha256`` is the identity and never dangles. ``image_id`` is a
    convenience pointer that is nulled if the picture is deleted, because the
    lock is a record of what happened and deleting a picture does not unmake the
    generation that consumed it. This is also what makes the reverse question,
    "which generations used this image", answerable before a deletion.

    Attributes:
        node_ref: Canonical node id of the node that did the resolving, so a
            workflow with two search nodes keeps their results apart.
        position: Order within that node's result set.
    """

    __tablename__ = "generation_input"

    generation_id: int = Field(
        sa_column=Column(
            "generation_id",
            Integer,
            ForeignKey("generation.id", ondelete="CASCADE"),
            primary_key=True,
        )
    )
    node_ref: str = Field(
        sa_column=Column("node_ref", String, primary_key=True),
    )
    position: int = Field(
        sa_column=Column("position", Integer, primary_key=True),
    )
    image_sha256: str = Field(
        sa_column=Column("image_sha256", String, nullable=False, index=True)
    )
    image_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            "image_id",
            Integer,
            ForeignKey("picture.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
    )
